
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author len0vo500
 */
public class SellStock extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    
    int ok=1;
    /**
     * Creates new form SellStock
     */
    public SellStock() {
        initComponents();
    }
     public SellStock(String Username) {
        super("Sell Stock");
        initComponents();
        conn = javaConnect.ConnecrDb();
        jLabel2.setText(Username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Select Ticker");

        jButton1.setText("Sell");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Current price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jButton1))
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(306, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(159, 159, 159)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Portfolio ob=new Portfolio(jLabel2.getText());
        ob.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //initComponents();
        conn = javaConnect.ConnecrDb();
        
        
        
        String U=jLabel2.getText();
        String Ticker=jTextField1.getText();
        float current_price=0;
        float total_shares=0;
        float L_Cash=0;
        
        //String current_price1=null;
       // String total_shares1=null;
         //jTextField2.setText("0");        
        String sql = "select Open from company where C_Ticker='"+Ticker+"'";
        try{
            conn.setAutoCommit(false);
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
               //jTextField2.setText(rs.getString(7));
                current_price=Float.parseFloat(rs.getString(1));
                //current_price1=rs.getString(1);
                //
                //rs.close();
               // pst.close();
            }
            //jTextField2.setText(current_price1);
             rs.close();
             pst.close();
            
            
          String sql1="select Total_Shares from portfolio1 where C_Ticker='"+Ticker+"' and username='"+U+"'";
           pst = conn.prepareStatement(sql1);
           rs = pst.executeQuery();
           while(rs.next())
           {
               total_shares=Float.parseFloat(rs.getString(1));
               jTextField2.setText(Float.toString(total_shares));
               //total_shares1=rs.getString(1);
           }
           rs.close();
           pst.close();
           
           String sql2="select L_cash from users where username='"+U+"'";
           pst = conn.prepareStatement(sql2);
           rs= pst.executeQuery();
           while(rs.next())
           {
               L_Cash=Float.parseFloat(rs.getString(1));
           }
           rs.close();
           pst.close();
           
           //float z=0;
           String sql4="update portfolio1 set Total_Shares=null, Profit_Loss=null where username='"+U+"' and C_Ticker='"+Ticker+"' and Total_Shares='"+total_shares+"'";
           pst = conn.prepareStatement(sql4);
           pst.execute();
           //rs.close();
           pst.close();
           
           // where Total_Shares='"+total_shares+"'
           String S="S";
           String sql5="insert into transaction_h(username,C_Ticker,Buy_Sell,price_share,Total_Shares) values('"+U+"','"+Ticker+"','"+S+"','"+current_price+"','"+total_shares+"')";
           //String sql5="insert into transaction_h(Username,C_Ticker,Buy_Sell,price_Share,Total_Shares) values(?,?,?,?,?) where Total_Shares='"+total_shares+"'";
          // String sql5="update transaction_h set Buy_Sell='"+S+"',Price_share='"+current_price+"',Total_Shares='"+total_shares+"' where username='"+U+"' and C_Ticker='"+Ticker+"'";
           pst = conn.prepareStatement(sql5);
           
           
           pst.execute();
           //rs.close();
           pst.close();
           //rs.close();
           
           
           L_Cash=L_Cash+(total_shares*current_price);
           
           String sql3="update users set L_Cash='"+L_Cash+"' where username='"+U+"'";
           pst= conn.prepareStatement(sql3);
           pst.execute();
           //rs.close();
           //pst.close();
           
           pst.close();
           //rs.close();
           //rs6.close();
        
           
          
           
           
           
           
           if(ok==1)
            {
                conn.commit();
                JOptionPane.showMessageDialog(null, "committed");
            }
                
            else
            {
                conn.rollback();
                JOptionPane.showMessageDialog(null, "rolled back");
            }
           
           conn.setAutoCommit(true);
           
           
           
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }   
        
        
        /*String sql2 = "select * from company where C_Ticker='"+Ticker+"'";
        try{
            pst = conn.prepareStatement(sql2);
            rs = pst.executeQuery();
            if(rs.next()){
               
                rs.close();
                pst.close();
            }
            else{
                JOptionPane.showMessageDialog(null, "Incorrect Username");
            }
            
        
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }   */
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
