
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dell
 */
public class UserDetailsA extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    
     public class Company{
        public String Username;
        public String F_Name;
        public String L_Name;
        public String L_Cash;
        public String Email;
        public String Mob_Number;
      
        
        public Company(String Username,String F_Name,String L_Name,String L_Cash,String Email,String Mob_Number)
        {
            this.Username=Username;
            this.F_Name=F_Name;
            this.L_Name=L_Name;
            this.L_Cash=L_Cash;
            this.Email=Email;
            this.Mob_Number=Mob_Number;
            
        }
    }
    /**
     * Creates new form UserDetailsA
     */
    public UserDetailsA() {
        initComponents();
    }
    
    public UserDetailsA(String UsernameA) {
        super("User Details for Admin");
        initComponents();
        conn = javaConnect.ConnecrDb();
        jLabel1.setText(UsernameA);
        
        
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        
        jLabel1.setText(UsernameA);
        //ArrayList<Company> list=ListCompany();
        
        ArrayList<Company> list =new ArrayList<>();
        conn = javaConnect.ConnecrDb();
        
        String sql = "select Username,F_Name,L_Name,L_Cash,Email,Mob_Number from users";
        try{
            //(select Username,F_Name,L_Name,L_Cash from users) as tt1
            String sql2 = "select count(Username) from users";
            
            
            pst = conn.prepareStatement(sql2);
            rs = pst.executeQuery();
            String a = null;
            if(rs.next()){
                a=rs.getString(1);
                jTextField1.setText(a);
            }
            int d=Integer.parseInt(a);
            rs.close();
            pst.close();
            
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
          
                Company [] c = new Company[d];
               for(int i=0;i<c.length; i++){
                   c[i] = new Company(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6));
                   rs.next();
               }
               for(int i=0; i<c.length;i++){
                   list.add(c[i]);
               }
            }
            
            
             rs.close();
             pst.close();
            
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }   
        
        Object rowData[]=new Object[6];
        for(int i=0;i<list.size();i++)
        {
            rowData[0]=list.get(i).Username;
            rowData[1]=list.get(i).F_Name;
            rowData[2]=list.get(i).L_Name;
            rowData[3]=list.get(i).L_Cash;
            rowData[4]=list.get(i).Email;
            rowData[5]=list.get(i).Mob_Number;
            
            model.addRow(rowData);
           
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "F_Name", "L_Name", "L_Cash", "Email", "Mob_Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "        ", "1", "2", "3", "4", " " }));

        jButton2.setText("Sort");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Number of Users");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        AdminHome ob=new AdminHome(jLabel1.getText());
        ob.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        ArrayList<Company> list = new ArrayList<>();
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        
        int rows = jTable1.getRowCount();
        
        model.setRowCount(0);
        
        /*for(int j=1;j<=rows;j++)
        {
            model.removeRow(j);
        }   */    
        
        conn = javaConnect.ConnecrDb();
        String Combo=(String) jComboBox1.getSelectedItem();
        
        int b=Integer.parseInt(Combo);
        String sql=null;
        //String sql = "select * from company order by '"+Combo+"'";
        switch(b)
        {
            case 1:
                 sql="select Username,F_Name,L_Name,L_Cash,Email,Mob_Number from users order by Username";
                 break;
            case 2:
                 sql="select Username,F_Name,L_Name,L_Cash,Email,Mob_Number from users order by F_Name";
                 break;
            case 3:
                 sql="select Username,F_Name,L_Name,L_Cash,Email,Mob_Number from users order by L_Name";
                 break;
            case 4:
                 sql="select Username,F_Name,L_Name,L_Cash,Email,Mob_Number from users order by L_Cash";
                 break;
        }
        try{
            
            String sql2 = "select count(Username) from users";
            
            
            pst = conn.prepareStatement(sql2);
            rs = pst.executeQuery();
            String a = null;
            if(rs.next()){
                a=rs.getString(1);
                jTextField1.setText(a);
            }
            int d=Integer.parseInt(a);
            rs.close();
            pst.close();
            
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
          
                Company [] c = new Company[d];
               for(int i=0;i<c.length; i++){
                   c[i] = new Company(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6));
                   rs.next();
               }
               for(int i=0; i<c.length;i++){
                   list.add(c[i]);
               }
            }
            
            
             rs.close();
             pst.close();
            
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }   
        
        Object rowData[]=new Object[6];
        for(int i=0;i<list.size();i++)
        {
            rowData[0]=list.get(i).Username;
            rowData[1]=list.get(i).F_Name;
            rowData[2]=list.get(i).L_Name;
            rowData[3]=list.get(i).L_Cash;
            rowData[4]=list.get(i).Email;
            rowData[5]=list.get(i).Mob_Number;
            
            model.addRow(rowData);
           
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDetailsA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDetailsA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDetailsA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDetailsA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDetailsA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
